### ISSUE TITLE
试试看vox能不能用

### ISSUE THREAD

**Issue by exxfzc** [XQS6LB3A/LyricsX#11]
好像好少人用呀,做吃螃蟹的第一人吧,效果到时再说!!

**Comment by XQS6LB3A** [comment]
亲测可用。

因为昨天刚发布正式版，还没有宣传。

有任何问题和建议欢迎提issue❤️

**Comment by exxfzc** [comment]
出师不利呀....一打开vox,lyricsx就自动退出.....
vox版本为2.8.19,mac商店下载的
未测试itunes

**Comment by XQS6LB3A** [comment]
“自动退出”是指LyricsX无法打开，还是在LyricsX运行时打开Vox，此时LyricsX退出？
若是前者，当时iTunes和Vox是否在运行？
若是后者，请问是否设置过偏好设置？

暂时无法复现，可否提供CrashLog？
