### ISSUE TITLE
建议在顶部菜单栏显示歌词的时候，隐藏 LyricsX 图标

### ISSUE THREAD

**Issue by bbbear2002** [XQS6LB3A/LyricsX#15]
建议在顶部菜单栏显示歌词的时候，隐藏 LyricsX 图标，这样可以节省宝贵的菜单栏空间

**Comment by XQS6LB3A** [comment]
我考虑过这个功能，但是有一个问题：歌词过长而剩余空间不足以显示时，图标会被系统自动隐藏。此时无法通过任何方式和程序交互。遂放弃。

**Comment by XQS6LB3A** [comment]
找到了一个检测菜单栏图标是否被系统隐藏的黑魔法，将在下一个版本加入。
