### ISSUE TITLE
iTunes 打开时，LyricsX 不能启动

### ISSUE THREAD

**Issue by bbbear2002** [XQS6LB3A/LyricsX#16]
设置随 iTunes 启动退出无效，且在 iTunes 打开时，LyricsX 不能启动

**Comment by XQS6LB3A** [comment]
一个已知的问题是，LyricsX打开时，iTunes无法退出。将在下一个版本修复

关于“在 iTunes 打开时，LyricsX 不能启动”，根据描述，可能是启动后立即崩溃，可否提供CrashLog？

CrashLog可在~/Library/Logs找到，形如LyricsX_DATE_USERNAME.crash

**Comment by CookieJaySJ** [comment]
新版本仍然出现了这个问题

**Comment by XQS6LB3A** [comment]
@CookieJaySJ 请详述问题状况，当前的偏好设置，以及复现步骤（如果有）

**Comment by CookieJaySJ** [comment]
当前设置就是勾选了跟随播放器启动和退出；选中iTunes。
但每次重启该app都会恢复到默认设置。

**Comment by CookieJaySJ** [comment]
先打开iTunes ，LyricsX不能自动启动；此时手动启动也不能。只能做到先打开LyricsX 再打开iTunes。

**Comment by XQS6LB3A** [comment]
@CookieJaySJ 未能重现。“恢复到默认设置”是指重启后自动取消勾选？

请确认是否是另一个问题： #25 iTunes 没有播放音乐时，LyricsX崩溃

**Comment by CookieJaySJ** [comment]
当我第一次运行之后，在勾选与iTunes退出打开选项的情况下：我退出iTunes时提醒我第一次运行LyricsXhelper，我点了确定后，LyricsX就自动退出了。然后再打开iTunes时，就算手动运行Lyrics，它也会自动退出。

**Comment by XQS6LB3A** [comment]
@CookieJaySJ 你的问题描述看起来和 #25 非常接近，请再次确认是否是 #25 

第一次退出显然是正常的随iTunes退出，而第二次退出是因为iTunes启动时处于停止状态（没有播放任何音乐），由于一个已知的问题，LyricsX将会崩溃。此问题将在下一个版本修复。
