### ISSUE TITLE
小白问题，依赖库怎么搞进去～

### ISSUE THREAD

**Issue by LiShengmin** [XQS6LB3A/LyricsX#27]

**Comment by XQS6LB3A** [comment]
https://github.com/Carthage/Carthage

**Comment by LiShengmin** [comment]
** Please update to the latest Carthage version: 0.22.0. You currently are on 0.21.0
*** Fetching SnapKit
*** Fetching SwiftyOpenCC
*** Fetching SwiftyJSON
*** Fetching EasyPreference
*** Checking out EasyPreference at "v0.2.0"
*** Checking out SnapKit at "3.2.0"
*** Checking out SwiftyJSON at "3.1.4"
*** Checking out SwiftyOpenCC at "v0.2.1"
*** xcodebuild output can be found in /var/folders/8y/xw0m79x505d0csq8ydb5hrkr0000gn/T/carthage-xcodebuild.jTXHbi.log
*** Building scheme "EasyPreference macOS" in EasyPreference.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/lishengmin/3rd/_Mac项目/LyricsX/Carthage/Checkouts/EasyPreference/EasyPreference.xcworkspace -scheme EasyPreference\ macOS -configuration Release -derivedDataPath /Users/lishengmin/Library/Caches/org.carthage.CarthageKit/DerivedData/EasyPreference/v0.2.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/8y/xw0m79x505d0csq8ydb5hrkr0000gn/T/carthage-xcodebuild.jTXHbi.log

使用Carthage update 报错想寻求解决办法
