### ISSUE TITLE
Spotify Beatles 的基本全部不同步

### ISSUE THREAD

**Issue by iamWangJunjie** [XQS6LB3A/LyricsX#28]
![如图](http://ww1.sinaimg.cn/large/006tNbRwly1ff2o2y7ev8j31km0swwk9.jpg)

4 首歌 3 首不同步：Yesterday、Hey Jude、Let It be。Ticket To Ride 可以显示歌词。

现在这样子几乎没办法用。

**Comment by iamWangJunjie** [comment]
![1](http://ww1.sinaimg.cn/large/006tNbRwly1ff2o2y7ev8j31km0swwk9.jpg)

**Comment by XQS6LB3A** [comment]
可在菜单栏中手动调节歌词时间偏移，或手动搜索歌词。
