### ISSUE TITLE
Please Adjust Priority of Lyrics Services Source

### ISSUE THREAD

**Issue by kikandychan** [XQS6LB3A/LyricsX#30]
For 163 providing the lyrics with Chinese translated lyrics, it would be much better to select the lyric from 163 instead of Xiami.
Or maybe you could allow us to change the priority

**Comment by XQS6LB3A** [comment]
Lyrics with translation do have a higher priority, as long as it matches artist and title.

I think correctness is more important. If there are perfectly matched lyrics and mismatched lyrics with translation, LyricsX will choose the former.

**Comment by kikandychan** [comment]
Thank you for your reply，you really helped me.
