### ISSUE TITLE
找不到以前超级好用的导入歌词到iTunes的功能了

### ISSUE THREAD

**Issue by ikaradise** [XQS6LB3A/LyricsX#31]
这个是有意去掉了吗？我觉得超级好用，能否在未来版本中加回来呢？

**Comment by ikaradise** [comment]
原来不是原来那个LyricsX了呀，那我就建议一下咯。谢谢

**Comment by ikaradise** [comment]
还有有时候一些轻音乐也会自动生成歌词（但实际上是没有的）。希望能有取消歌词的选项。

**Comment by XQS6LB3A** [comment]
拖动歌词文件到歌词窗口中即可导入歌词

**Comment by XQS6LB3A** [comment]
已完成写入iTunes功能，将在下一个版本发布。

自动写入功能尚未开发，你可以关注 #48 以了解最新进展。
