### ISSUE TITLE
Karaoke lyrics window do not work on MacBook 2011

### ISSUE THREAD

**Issue by gayathriw** [XQS6LB3A/LyricsX#34]
The karaoke lyrics window is showing on my imac, but not on my macbook pro.

**Comment by XQS6LB3A** [comment]
Did you mean LyricsX work properly on your iMac, but not work on your MacBook?

**Comment by gayathriw** [comment]
yes exactly, the karaoke lyrics overlay is showing on my imac, but not on my 2011 macbook pro. It is enabled (checkmarked) in both. The other lyrics window works fine, as well as menu bar lyrics.

**Comment by gayathriw** [comment]
Also note I'm using Sierra on both the imac and macbook pro.

**Comment by gayathriw** [comment]
If you need any more information, logs, whatever, do let me know! thx

**Comment by XQS6LB3A** [comment]
Actually I have no ideal about this issue. It seems to appear only on specific devices, and I can't reproduce it. The rest of the part works fine, so there's no crash log.

It might be the same issue as #13 , which has disappeared for a long time.

**Comment by gayathriw** [comment]
Hmm ok, perhaps add some extra logging statements around the area of code where it's called to display so that it can be tracked down?

**Comment by XQS6LB3A** [comment]
I've just completely rewrote karaoke lyrics, please check [this version](https://github.com/XQS6LB3A/LyricsX/releases/tag/v1.1.4-beta).
