### ISSUE TITLE
切换桌面时菜单栏歌词不显示

### ISSUE THREAD

**Issue by jincai** [XQS6LB3A/LyricsX#36]
切换桌面时发现菜单栏的歌词不显示了，切回到之前的桌面也不会显示，只有关闭菜单栏显示功能再重新打开才可以。
后来发现好像是有chrome的桌面，然后滚动下chrome的页面，歌词就不显示了。

**Comment by XQS6LB3A** [comment]
未能复现。
不显示是指完全没有任何显示，还是显示省略号，还是显示应用图标？
切换的两个workspace是桌面还是全屏应用？
这种情况只和chrome相关吗，其他情况下出现过吗？

**Comment by jincai** [comment]
1、不显示是指的只的省略号
2、Spotify和chrome是最大化(最大化用的是moom)，只有菜单栏显示，Dock是自动显示和隐藏的。
3、又试了下，不是和chrome相关，和切换桌面也没关系。
复现步骤
1、在一个桌面打开，打开Spotify和lyric，Spotify使用Moom最大化，播放我们都去过很多地方的这首歌，单曲循环播放，Lyrics设置启用菜单栏歌词，其余不启用，这时候正常显示。然后最小化Spotify，在桌面上使用touchpad点击下，菜单栏图标变成三个点。

**Comment by jincai** [comment]
找到问题了，跟一个Showyedge的软件服务（切换输入法时在菜单栏显示）有关。
另外即使退出了Showyedge，点击通知中心的图标也会导致菜单栏图标变成三个点。

**Comment by latte-z** [comment]
同样遇到这个问题，我是老LyricsX用户，安装这个之前用CMM彻底删除了安装这个新的。
发现菜单栏歌词无论怎么设置，重启也无果，永远都是省略号图标。
iTunes、Spotify均无法正常显示菜单栏歌词，逐行歌词的阴影颜色默认也是无效的，自己再设置一次就好了。
目前是接了一个显示器使用的，不清楚是不是这个问题，但是拔掉后重启还是省略号。

另外有一个建议是增加屏幕歌词显示选择，双屏的话目前是在焦点屏幕启动就固定在那个位置了。

**Comment by XQS6LB3A** [comment]
首先解释一下省略号出现的原因。
根据 #15 ，我将菜单栏歌词作为应用图标以节约显示空间。问题在于如果歌词太长，图标将自动被系统隐藏以至于完全无法和应用交互。
于是我使用了一个黑魔法来检测图标是否显示在屏幕上，如果不在，则自动从尾部截断歌词，直到能显示在屏幕上为止。你可以尝试在小屏幕设备上打开Xcode等菜单栏超长的应用，比较容易看到截断的效果。
这样处理有几个已知的问题：
1. 全屏应用不显示菜单栏，同样不显示应用图标，导致歌词无限截断，最后剩下一个省略号。
2. 系统定位图标会导致黑魔法失效，同样产生无限截断。
3. 兼容性问题，例如你说的Showyedge。

这些问题都是难以解决的，但是我不会放弃歌词截断的功能。或许我可以提供一个选项用于回退到1.1.0的显示策略（显示独立的应用图标和歌词，这样即使歌词被隐藏也没关系）

**Comment by XQS6LB3A** [comment]
@latte-z 闪退问题参见 #25 ，将在下一个版本修复

关于双屏下的各种问题，很抱歉，我没有外接显示器。我既不知道问题是什么样子，也无从得知哪些改动会达到怎样的效果，恐怕这类问题都无法解决了。
你可以新开一个issue，我打上标签以寻求帮助。

**Comment by latte-z** [comment]
@XQS6LB3A 谢谢回复，可惜自己不会Swift和OSX的开发，要不然可以试着着手解决一下~

歌词显示屏幕的问题不大，主要还是那个菜单栏显示的问题。因为无论我是否接上屏幕都是省略号...大概是也遇上了什么兼容性冲突，我来排查一下

**Comment by jincai** [comment]
另外还有一个崩溃的bug，日志太多，就不直接贴上来了，放在了notepad.live上
http://notepad.live/share/650833raeu80

**Comment by XQS6LB3A** [comment]
已在v1.1.2修复
