### ISSUE TITLE
[feature request]希望能自己设定歌词位置

### ISSUE THREAD

**Issue by cogitoxin** [XQS6LB3A/LyricsX#37]
超级感谢开发！这个比dynamic lyrics好用多了！

唯一美中不足的就是之前一直习惯把歌词放在桌面右下角，并且单行显示，现在变成了中间两行非常不习惯，希望能自己设定歌词显示位置和行数。

再次感谢！

**Comment by XQS6LB3A** [comment]
v1.1.3 可以调整歌词位置。单行歌词还在开发。

**Comment by cogitoxin** [comment]
@XQS6LB3A 感谢！但是刚刚试了一下发现位置只能上下调，不能左右调……系统10.12.2
<img width="712" alt="screen shot 2017-05-25 at 10 10 20" src="https://cloud.githubusercontent.com/assets/16520525/26453626/68919a1e-4132-11e7-9fee-bbc2be8aa90e.png">

**Comment by XQS6LB3A** [comment]
中间方格周围的四根红线可以点击，以设置相应的约束是否生效

**Comment by cogitoxin** [comment]
@XQS6LB3A 可以了！超级感谢！

**Comment by Halomaple** [comment]
控制距离生效的那个图标，建议改为勾☑️这种。打上☑️了就意味着距离生效。那个‘工’字红线太难注意到啦。

**Comment by ddddxxx** [comment]
@Halomaple 我倾向使用 #52 的方案，修改数字后立刻激活对应的约束。
