### ISSUE TITLE
V1.1.1 Menu Bar 歌词无法显示

### ISSUE THREAD

**Issue by pokieyang** [XQS6LB3A/LyricsX#39]
<img width="402" alt="screen shot 2017-05-01 at 10 19 30 pm" src="https://cloud.githubusercontent.com/assets/26211623/25581968/67308dba-2ebd-11e7-8c38-4997940b7d69.png">
左为V1.1.0 右为V1.1.1

**Comment by pokieyang** [comment]
可能原因是与 Bartender 不兼容导致，显示长度很短，隐藏部分释放之后便无法显示
<img width="1440" alt="screen shot 2017-05-01 at 10 52 29 pm" src="https://cloud.githubusercontent.com/assets/26211623/25582640/e24c522e-2ec0-11e7-8411-ffe6aa7f38d8.png">
<img width="1440" alt="screen shot 2017-05-01 at 10 52 53 pm" src="https://cloud.githubusercontent.com/assets/26211623/25582658/f4f08e2c-2ec0-11e7-88ac-a3ba7df48d27.png">

**Comment by XQS6LB3A** [comment]
没有足够空间显示时，歌词会自动截断，参见 #36 
下一个版本将提供类似“回退到1.1.0的显示方案”的选项。

**Comment by pokieyang** [comment]
这样啊，那就期待下一版本咯～
