### ISSUE TITLE
sandbox violation for user defined lyrics saving path after program restart

### ISSUE THREAD

**Issue by chyiz** [XQS6LB3A/LyricsX#43]
I believe this is not a regression, but has been there for a while.
I set my lyrics saving path to a different location, and it worked fine for that program session. But if I restart the program, it's not able to read and write my lyrics folder anymore, and I got sandbox violation messages in my console.

I tried to debug the program, and found that at least `url.startAccessingSecurityScopedResource()` in Extension.swift:91 still returns true.  So I'm out of ideas.

**Comment by XQS6LB3A** [comment]
fixed on dev branch, I prematurely stopped accessing.
