### ISSUE TITLE
进程CPU占用率略高

### ISSUE THREAD

**Issue by dingdangnao** [XQS6LB3A/LyricsX#44]
播放器关闭时占用率在11% 12%左右
播放器打开播放歌曲时占用率大约在18%~25%之间，觉得有些高
_rmbp mid2015 i7_

**Comment by XQS6LB3A** [comment]
在我的设备上，CPU占用率没有超过3%。(_rmbp late2013 i5_)
18%不是正常状况。请提供更多信息
- 系统和软件版本
- 使用的音乐播放器
- LyricsX 的取样结果

**Comment by dingdangnao** [comment]
系统 macOSmacOS 10.12.4
软件版本 1.2.2(1064)
使用中的播放器 iTunes和Spotify (同时开启)
取样结果 [“LyricsX”的取样.txt](https://github.com/XQS6LB3A/LyricsX/files/981293/LyricsX.txt) (此时占用率在14%左右)

**Comment by XQS6LB3A** [comment]
已重现，当所有的音乐播放器处于停止状态，并且`首选音乐播放器`为自动选择时，CPU占用率偏高。此时程序会反复确认每一个播放器的状态，试图找到正在播放的一个。

将在下一个版本修复。在此之前，手动选择首选播放器可以缓解这个问题。
