### ISSUE TITLE
有些国外歌手无法搜索到歌词

### ISSUE THREAD

**Issue by Arrow-Li** [XQS6LB3A/LyricsX#45]
像Ed Sheeran的歌就不行(翻译成艾德·希兰)，但是Adele(翻译成阿黛尔)的歌就可以正常搜索到。
同时在菜单栏点击搜索歌词会崩溃
[crash.txt](https://github.com/XQS6LB3A/LyricsX/files/981309/crash.txt)

**Comment by Arrow-Li** [comment]
Ed Sheeran的Dive实际上搜索到的是他的I See Fire
![123](https://cloud.githubusercontent.com/assets/17962902/25777917/d69fc1ae-3320-11e7-8a19-d2324b339235.jpg)

**Comment by XQS6LB3A** [comment]
见 #29 ，搜索结果完全取决于歌词源，是程序无法控制的。相关的讨论还有 #20

**Comment by Arrow-Li** [comment]
手动搜索会程序崩溃，见crash.txt

**Comment by XQS6LB3A** [comment]
程序崩溃是每次必然发生还是随机发生，重启程序能否解决？
crashlog显示crash发生在构建UI过程中，但是这部分是由interface builder做的，理论上不会出错。请尝试重装程序？

**Comment by Arrow-Li** [comment]
必然，无论什么歌点搜索歌词都会崩溃

**Comment by XQS6LB3A** [comment]
已确认，将在下一个版本修复
