### ISSUE TITLE
希望能够设置网络代理开关

### ISSUE THREAD

**Issue by RCD-Y** [XQS6LB3A/LyricsX#46]
有时候开了代理的时候搜索不到歌词，十分麻烦，希望能够在设置中增添不使用代理的选项。

**Comment by XQS6LB3A** [comment]
我认为这超出了一个歌词软件应有的功能。用户既然使用了代理，决定哪些软件使用代理也是用户的责任。这对软件来说是完全透明的。

以下是 LyricsX 使用的歌词服务器的地址，你可以自行添加规则。
- 126.net
- 163.com
- gecimi.com
- kugou.com
- qq.com
- ttpod.com
- xiami.com
- xiami.net
