### ISSUE TITLE
不能跟随iTunes启动

### ISSUE THREAD

**Issue by leochenwei** [XQS6LB3A/LyricsX#47]
我安装LyricsX以后不能跟随iTunes启动，设置里选择的是iTunes，点选了跟随播放器启动和退出。打开iTunes播放音乐以后还是不启动，需要手动打开。退出iTunes时可以跟随播放器一起退出。我的Mac OS 10.12.5，iTunes 12.6.1.25。

**Comment by XQS6LB3A** [comment]
自动启动的功能是由一个独立的应用程序完成的，名为`LyricsXHelper`。它监视播放器的运行情况并在合适的时机启动 LyricsX。

请打开活动监视器并搜索`LyricsXHelper`，确认各种情况下的运行状况。

**Comment by leochenwei** [comment]
我打开活动监视器，打开iTunes播放音乐，退出iTunes时，LyricsX进程变成LyricsXHelper，正常退出。
但是我再次打开iTunes并播放音乐时，LyricsXHelper进程不会打开LyricsX进程,LyricsX也不会运行。需要手动运行LyricsX程序，才会显示歌词，反复试了好几遍了

**Comment by XQS6LB3A** [comment]
无法复现，请提供更多信息

启动iTunes时，LyricsX不会启动，此时LyricsXHelper会退出吗？有响应吗？
手动启动LyricsX之后，LyricsXHelper会退出吗？

有可能是偏好设置未能同步，请尝试切换`首选音乐播放器`至`自动`，然后切换回来。
此外，若LyricsXHelper启动时iTunes处于启动状态，则LyricsXHelper会先等待iTunes退出，再进行正常检测。

**Comment by lvhe19880210** [comment]
出现相同问题，只能一块推出不能一起启动，但是我没有出现“退出iTunes时，LyricsX进程变成LyricsXHelper”这个现象而是在退出iTunes时仅仅lyricsxX退出而已，LyricsX Helper.app并没有同时出现，然后我尝试在iTune退出后到安装包里双击LyricsXHelper.app，但活动监视器也依旧并没有显示这个app在运行，也就是说在任何情况下我都无法在活动监视器上找到LyricsXHelper.app
![Uploading 屏幕快照 2017-06-05 上午12.39.10.png…]()


macos：10.12.5 (16F73) itunes：12.6.1.25

**Comment by lvhe19880210** [comment]
![2017-06-05 12 39 10](https://cloud.githubusercontent.com/assets/29178968/26763653/dc110ad4-4988-11e7-86e1-8e10ef6360b9.jpeg)

- 

- [ ]

**Comment by lvhe19880210** [comment]
<img width="1281" alt="2017-06-05 12 39 10" src="https://cloud.githubusercontent.com/assets/29178968/26763669/392d7a40-4989-11e7-9708-17dff6c49457.png">

**Comment by lvhe19880210** [comment]
<img width="1281" alt="2017-06-05 12 39 10" src="https://cloud.githubusercontent.com/assets/29178968/26763672/4cf5066a-4989-11e7-85bc-369a8c51e70e.png">

**Comment by lvhe19880210** [comment]
附图是我启动itunes时lyricx没有随之一块启动的截屏， 还有重要的要说的一点是我选择了只在menu bar显示歌词而不是在桌面显示，但我再次启动lyric X时这个保存没有了又得重新选，我不知道这个问题跟lyricxhelper异常有没有关系所以就先在这个话题下说一下而没开新话题

**Comment by breezehome** [comment]
估计没有保存设置，导致重新启动又需要重新设置

**Comment by XQS6LB3A** [comment]
@lvhe19880210 #16 已修复，应该是别的问题。请新开一条issue，我将跟踪解决。

**Comment by lvhe19880210** [comment]
OK
ddddxxx <notifications@github.com>于2017年6月5日 周一上午9:38写道：
