### ISSUE TITLE
希望可以增加将歌词写入文件标签功能

### ISSUE THREAD

**Issue by dingdangnao** [XQS6LB3A/LyricsX#48]
比如说当判断播放文件为本地iTunes或者Vox的时候，可以将歌词自动写入歌曲的标签里。。。

**Comment by XQS6LB3A** [comment]
v1.1.3 可以手动写入歌曲 ID3。自动写入功能随后开发。

由于 Vox 并没有开放相关接口，目前仅能写入到 iTunes。

**Comment by oscar-c** [comment]
这个功能能不能默认开启？

**Comment by oscar-c** [comment]
另外，写入歌词的时候希望能够删去开头和最后的多余换行符、空格等。
有些歌词开头的地方会多空出一行来。

**Comment by oscar-c** [comment]
另外，写入歌词之后，似乎不会触发iTunes Music Library的同步功能，需要手动编辑并保存，写入的歌词才会自动同步到云端，并在iOS上能够查看到

**Comment by XQS6LB3A** [comment]
@oscar-c [版本1.1.4-beta](https://github.com/XQS6LB3A/LyricsX/tree/v1.1.4-beta)可以自动写入歌词

> 写入歌词的时候希望能够删去开头和最后的多余换行符、空格等。

感谢建议，将在下一版本添加这一功能

> 写入歌词之后，似乎不会触发iTunes Music Library的同步功能

iTunes 只提供了唯一的 API，也没有涉及到 Library 同步。这一功能似乎无法完成。
我会留心相关信息。你可以新开一条 issue 用于跟踪 Library 同步相关功能。

**Comment by oscar-c** [comment]
> 另外，写入歌词的时候希望能够删去开头和最后的多余换行符、空格等。
> 有些歌词开头的地方会多空出一行来。

目前来看的话，自动写入的歌词在最后会多出一行

**Comment by ddddxxx** [comment]
@oscar-c 本问题已得到了解决。我仍然建议你新开一条issue用于跟踪去空格相关功能。
