### ISSUE TITLE
跟随播放器启动和退出无效

### ISSUE THREAD

**Issue by Cople** [XQS6LB3A/LyricsX#50]
需要手动退出和启动（试了 iTunes 和 VOX）。

退出后`LyricsX`进程不见，`LyricsXHelper `没有出现。

**Comment by XQS6LB3A** [comment]
`LyricsXHelper`不支持 macOS 10.11，将在下一个版本修复。

**Comment by lvhe19880210** [comment]
@XQS6LB3A macos 10.12又重新出现这个问题 而且每次打开app都会恢复默认设置 跟issue16一样
