### ISSUE TITLE
希望可以自订歌词来源于优先级

### ISSUE THREAD

**Issue by yupolee** [XQS6LB3A/LyricsX#53]
首先感谢开发如此优秀的歌词软件～

最近再用 Spotify 听歌的时候（周杰伦为主），获取的第一歌词总是不正确，搜索时发现都是来源于 TTPod ，总是需要手动切换到163的歌词。

由此希望可以增加**歌词来源优先级**的选项，使用正确率更高的来源。

**Comment by hoholee** [comment]
啊抱歉没看到closed issue -_- 谢谢回复！
