### ISSUE TITLE
不支持 iTunes12.3.3.17. 所以并不是向下兼容的？

### ISSUE THREAD

**Issue by kikandychan** [XQS6LB3A/LyricsX#54]
版本 iTunes12.3.3.17
歌词软件似乎完全无法检测到当前在播放音乐，搜索歌词里面曲目艺人都是空白的

**Comment by XQS6LB3A** [comment]
iTunes API 可能更改过。我这里并没有低版本的 iTunes 可供测试，可否帮忙测试以下脚本：
```applescript
tell application "iTunes" to get "id: " & id of current track & "
name: " & name of current track & "
album: " & album of current track & "
artist: " & artist of current track
```
方法是在`Script Editor.app`中运行，结果会显示在底部。

**Comment by kikandychan** [comment]
你好，我后来升级到 12.4.3.1 lyricsX 可以用了。
在这个版本下，结果是:
"id: 21548
name: Right Now (feat. Chris Brown)
album: Wa To Yo
artist: AI”
问题里提到的 iTunes 12.3.3.17 是我把 MacBook 完全格式化后重新下载的出厂时的系统。
我去找找这个版本的 iTunes，不过好像很难找到了。


With many regards,
Andy Chan

**Comment by kikandychan** [comment]
找到了那个版本的 iTunes，报错结果如下：
error "不能将“id of «class pTrk» of application \"iTunes\"”转换为“Unicode text”类型。" number -1700 from id of «class pTrk» to Unicode text


With many regards,
Andy Chan

**Comment by XQS6LB3A** [comment]
感谢回复！

所以这似乎是 iTunes 的接口更改过。我并没有此版本的iTunes，可否帮忙生成旧版 iTunes 的接口文件？

你可以运行以下命令：
```
$ sdef /path/to/iTunes | sdp -fh --basename iTunes
```
请将 `/path/to/iTunes` 替换为 iTunes 的路径。此命令将在当前目录生成`iTunes.h`，请将此文件发送给我。
