### ISSUE TITLE
“LyricsX”の開発元を確認できないため、開けません。

### ISSUE THREAD

**Issue by syhily** [XQS6LB3A/LyricsX#61]
![image](https://user-images.githubusercontent.com/1761698/27598473-37328308-5b2b-11e7-83e1-6c2e20bb3c94.png)

**Comment by syhily** [comment]
Solved by open from the application folder.

**Comment by XQS6LB3A** [comment]
LyricsX will available on the Mac App Store soon.

By the way, you can always right click the application and select `Open` to open a non App Store applicarion.
