### ISSUE TITLE
请问我要如何制作歌词，网上的歌词目录已经没有了

### ISSUE THREAD

**Issue by gaochengyidlmu** [XQS6LB3A/LyricsX#63]

**Comment by XQS6LB3A** [comment]
抱歉，LyricsX 尚不提供歌词制作功能。你可以使用第三方工具制作歌词后导入 LyricsX。方法是将歌词文本或文件拖入歌词窗口，将自动作为当前音乐的歌词导入。

**Comment by gaochengyidlmu** [comment]
好的，谢谢

**Comment by XQS6LB3A** [comment]
内建歌词制作功能已列入开发计划，请关注 #65 以了解最新进展。
