### ISSUE TITLE
能否在设置中加入歌词来源的优先级设定？

### ISSUE THREAD

**Issue by hoholee** [XQS6LB3A/LyricsX#64]
如题，个人使用spotify的时候发现很多歌歌词会出错，打开歌词查找器发现大部分情况下是TTpod来源的歌词跳到了另一首歌，其它来源的歌词是正确的，允许用户选择歌词来源的优先级（或者是更直接的开关选项）也许能使歌词显示准确度提高？另一方面某些来源的歌词可能质量更高，允许设置来源的优先级也能满足一部分对来源有偏好的用户。

**Comment by XQS6LB3A** [comment]
见#53，已于 1.1.4 版本实现这一功能。可在实验室中设定。
