### ISSUE TITLE
标记为错误歌词后仍然自动搜索歌词

### ISSUE THREAD

**Issue by Moonboyzx** [XQS6LB3A/LyricsX#70]
非常感谢你，这个插件是我梦寐以求的歌词插件。再增加“标记此歌曲为不显示”的功能就更加完美了，有一些音乐是我收藏的纯音乐，这类音乐没有歌词，但是每次都会匹配一些不明所以的歌词。还有就是希望加个在Finder中显示的功能，方便自己编辑lrc

**Comment by XQS6LB3A** [comment]
见 #24。 下拉菜单中“错误的歌词”即为这一功能。

**Comment by Moonboyzx** [comment]
但是重新启动之后还是会有歌词

**Comment by XQS6LB3A** [comment]
这是预料之外的情况，我会尝试修复这个问题。

**Comment by Moonboyzx** [comment]
已经标记为错误歌词，同一首歌曲在其他播放列表中播放依然会有歌词

**Comment by ddddxxx** [comment]
在同一播放列表中播放时有歌词吗？

错误歌词是按照歌曲名和歌手标记的，没有播放列表的信息。按理说不会出现这样的情况

**Comment by ddddxxx** [comment]
关于“在Finder中显示”的功能，请新开一个issue以便跟踪解决。

PS：以后会推出应用内编辑歌词的功能，敬请期待
